# Generated by Django 5.1.6 on 2025-02-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='place',
            table='destinations',
        ),
    ]
