# Generated by Django 5.1.6 on 2025-02-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_place_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Destination',
        ),
    ]
